import { test, expect } from '@playwright/test';
import { registerAndLogin, uniqueEmail } from './helpers';

// Uses real local API responses in the disposable test database, not production.
for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
  test.describe(`acquisition screening ${viewport.width}px`, () => {
    test.use({ viewport });
    test('screens saved facts, switches profiles, and keeps diligence unknown', async ({ page }) => {
      const registration = page.waitForResponse(res => res.url().includes('/auth/register') && res.request().method() === 'POST');
      await registerAndLogin(page, uniqueEmail());
      const credentials = await (await registration).json();
      const created = await page.request.post('http://localhost:8000/v1/deals', {
        headers: { Authorization: `Bearer ${credentials.access_token}` },
        data: { name: 'Screening QA fixture', city: 'Columbus', state: 'OH', asking_price: 2500000,
          sq_ft: 15000, units: 24, year_built: 1990, property_type: 'Retail', source: 'Local browser test' },
      });
      expect(created.ok()).toBeTruthy();
      const deal = await created.json();
      await page.goto(`/deal/${deal.id}`);
      await expect(page.getByText('Not calculated', { exact: true })).toHaveCount(4);
      const panel = page.getByRole('region', { name: 'Acquisition buy-box screen' });
      await expect(panel.getByText('Diligence required: 3 pass, 0 fail, 2 unknown')).toBeVisible();
      const retailResponse = page.waitForResponse(res => res.url().includes('/acquisition-screen?') && res.url().includes('small_bay_retail'));
      await panel.getByLabel('Profile').selectOption('small_bay_retail');
      expect((await retailResponse).headers()['cache-control']).toBe('no-store');
      await expect(panel.getByText('Occupancy', { exact: true })).toBeVisible();
      await panel.getByLabel('Target city').fill('Columbus');
      await panel.getByLabel('State', { exact: true }).fill('O');
      await expect(panel.getByRole('button', { name: 'Apply' })).toBeDisabled();
      await panel.getByLabel('State', { exact: true }).fill('OH');
      await panel.getByRole('button', { name: 'Apply' }).click();
      await expect(panel.getByText('Diligence required: 4 pass, 0 fail, 14 unknown')).toBeVisible();
      await panel.getByLabel('Target city').fill('Cleveland');
      await panel.getByRole('button', { name: 'Apply' }).click();
      await expect(panel.getByText('Outside recorded criteria: 3 pass, 1 fail, 14 unknown')).toBeVisible();
      const occupancy = panel.locator('li').filter({ has: page.getByText('Occupancy', { exact: true }) });
      await expect(occupancy).toContainText('unknown');
      await expect(occupancy).toContainText('Not established');
      const downloadEvent = page.waitForEvent('download');
      await panel.getByRole('button', { name: 'Download acquisition screen' }).click();
      const download = await downloadEvent;
      expect(download.suggestedFilename()).toBe('acquisition-screen.json');
      const stream = await download.createReadStream();
      if (!stream) throw new Error('Acquisition screen download has no content');
      const chunks: Buffer[] = [];
      for await (const chunk of stream) chunks.push(Buffer.from(chunk));
      const snapshot = JSON.parse(Buffer.concat(chunks).toString('utf8'));
      expect(snapshot.screen.counts).toEqual({ pass: 3, fail: 1, unknown: 14 });
      expect(snapshot.screen.evidence_verified).toBe(false);
      expect(snapshot.target_market).toEqual({ city: 'Cleveland', state: 'OH' });
      await panel.getByText('Screening history', { exact: true }).click();
      await expect(panel.getByRole('button', { name: /^Download saved screen/ })).toHaveCount(1);
      const historyDownload = page.waitForEvent('download');
      await panel.getByRole('button', { name: /^Download saved screen/ }).click();
      const historyStream = await (await historyDownload).createReadStream();
      if (!historyStream) throw new Error('Historical screen download missing');
      const historyChunks: Buffer[] = [];
      for await (const chunk of historyStream) historyChunks.push(Buffer.from(chunk));
      expect(Buffer.concat(historyChunks).equals(Buffer.concat(chunks))).toBeTruthy();
      await panel.locator('details').screenshot({ path: `/private/tmp/acquisition-history-${viewport.width}.png` });
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
      await panel.scrollIntoViewIfNeeded();
      await page.screenshot({ path: `/private/tmp/acquisition-screen-${viewport.width}.png`, fullPage: true });
      await panel.getByRole('button', { name: 'New buy box' }).click();
      const form = panel.getByRole('form', { name: 'New acquisition buy box' });
      await expect(form.getByRole('button', { name: 'Save buy box' })).toBeDisabled();
      await form.getByLabel('Asset profile').selectOption('small_bay_retail');
      await expect(form.getByLabel('Minimum SF')).toHaveValue('8000');
      await form.getByLabel('Asset profile').selectOption('small_multifamily');
      await form.getByLabel('Market city').fill('Columbus');
      await form.getByLabel('Market state').fill('OH');
      await form.getByLabel('Minimum units').fill('40');
      await expect(form.getByRole('button', { name: 'Save buy box' })).toBeDisabled();
      await form.getByLabel('Minimum units').fill('20');
      await form.getByLabel('Maximum units').fill('30');
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
      await form.screenshot({ path: `/private/tmp/acquisition-create-${viewport.width}.png` });
      const createdBoxResponse = page.waitForResponse(res => res.url().endsWith('/buy-box') && res.request().method() === 'POST');
      await form.getByRole('button', { name: 'Save buy box' }).click();
      const savedBox = await createdBoxResponse;
      expect(savedBox.ok()).toBeTruthy();
      const box = await savedBox.json();
      await expect(panel.getByText('Diligence required: 4 pass, 0 fail, 1 unknown')).toBeVisible();
      await page.reload();
      await panel.getByText('Screening history', { exact: true }).click();
      await expect(panel.getByRole('button', { name: /^Download saved screen/ })).toHaveCount(1);
      await expect(panel.getByRole('option', { name: /Columbus.*Multifamily/ })).toBeAttached();
      await panel.getByLabel('Saved buy box').selectOption(box.id);
      await expect(panel.getByText('Diligence required: 4 pass, 0 fail, 1 unknown')).toBeVisible();
      await expect(panel.getByLabel('Target city')).toHaveCount(0);
      const savedDownloadEvent = page.waitForEvent('download');
      await panel.getByRole('button', { name: 'Download acquisition screen' }).click();
      const savedStream = await (await savedDownloadEvent).createReadStream();
      if (!savedStream) throw new Error('Saved criteria export missing');
      const savedChunks: Buffer[] = [];
      for await (const chunk of savedStream) savedChunks.push(Buffer.from(chunk));
      const savedSnapshot = JSON.parse(Buffer.concat(savedChunks).toString('utf8'));
      expect(savedSnapshot.screen.buy_box_id).toBe(box.id);
      expect(savedSnapshot.screen.criteria_snapshot.min_size).toBe(20);
      await expect(panel.getByRole('button', { name: /^Download saved screen/ })).toHaveCount(2);
      await page.getByText('Diligence excerpts', { exact: true }).click();
      const excerptForm = page.getByRole('form', { name: 'Add diligence excerpt' });
      await excerptForm.getByLabel('Source title').fill('Redacted pilot rent roll');
      await excerptForm.getByLabel('Source date').fill('2026-09-01');
      await excerptForm.getByLabel('Page or section').fill('Page 1, suite A');
      await excerptForm.getByLabel('Excerpt', { exact: true }).fill('Suite A: annual base rent $24,000.');
      await expect(excerptForm.getByRole('button', { name: 'Save excerpt' })).toBeDisabled();
      await excerptForm.getByRole('checkbox').check();
      await excerptForm.getByRole('button', { name: 'Save excerpt' }).click();
      const excerpt = page.getByRole('region', { name: 'Selected diligence excerpt' });
      await expect(excerpt).toContainText('Suite A: annual base rent $24,000.');
      await expect(excerpt).toContainText('SHA-256:');
      const reviewForm = excerpt.getByRole('form', { name: 'Review selected excerpt' });
      await expect(reviewForm.getByRole('button', { name: 'Save review' })).toBeDisabled();
      await reviewForm.getByLabel('Review rationale').fill('One suite does not establish whole-property occupancy.');
      await reviewForm.getByRole('button', { name: 'Save review' }).click();
      await expect(excerpt.getByText('Occupancy · inconclusive', { exact: true })).toBeVisible();
      await excerpt.getByRole('region', { name: 'Diligence criterion reviews' }).screenshot({ path: `/private/tmp/diligence-review-${viewport.width}.png` });
      await expect(panel.getByText('Diligence required: 4 pass, 0 fail, 1 unknown')).toBeVisible();
      await excerpt.screenshot({ path: `/private/tmp/diligence-excerpt-${viewport.width}.png` });
      await excerptForm.screenshot({ path: `/private/tmp/diligence-form-${viewport.width}.png` });
      await page.reload();
      await page.getByText('Diligence excerpts', { exact: true }).click();
      await page.getByRole('button', { name: 'Redacted pilot rent roll' }).click();
      await expect(excerpt).toContainText('Suite A: annual base rent $24,000.');
      await expect(excerpt.getByText('Occupancy · inconclusive', { exact: true })).toBeVisible();
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
      await panel.getByLabel('Saved buy box').selectOption(box.id);
      const evidenceDownloadEvent = page.waitForEvent('download');
      await panel.getByRole('button', { name: 'Download acquisition screen' }).click();
      const evidenceStream = await (await evidenceDownloadEvent).createReadStream();
      if (!evidenceStream) throw new Error('Evidence-bearing export missing');
      const evidenceChunks: Buffer[] = [];
      for await (const chunk of evidenceStream) evidenceChunks.push(Buffer.from(chunk));
      const evidenceBytes = Buffer.concat(evidenceChunks);
      const evidenceSnapshot = JSON.parse(evidenceBytes.toString('utf8'));
      expect(evidenceSnapshot.schema_version).toBe('acquisition-screen-export-v2');
      expect(evidenceSnapshot.screen.counts).toEqual({ pass: 4, fail: 0, unknown: 1 });
      expect(evidenceSnapshot.diligence_reviews.has_more).toBe(false);
      expect(evidenceSnapshot.diligence_reviews.changes_screening_result).toBe(false);
      expect(evidenceSnapshot.diligence_reviews.items).toHaveLength(1);
      const review = evidenceSnapshot.diligence_reviews.items[0];
      expect(review.criterion).toBe('occupancy');
      expect(review.snapshot.assessment).toBe('inconclusive');
      expect(review.snapshot.evidence.text).toBe('Suite A: annual base rent $24,000.');
      expect(review.snapshot.evidence.locator).toBe('Page 1, suite A');
      expect(review.snapshot.evidence.text_sha256).toMatch(/^[a-f0-9]{64}$/);
      await page.reload();
      await panel.getByText('Screening history', { exact: true }).click();
      await expect(panel.getByRole('button', { name: /^Download saved screen/ })).toHaveCount(3);
      const retainedDownloadEvent = page.waitForEvent('download');
      await panel.getByRole('button', { name: /^Download saved screen/ }).first().click();
      const retainedStream = await (await retainedDownloadEvent).createReadStream();
      if (!retainedStream) throw new Error('Retained evidence export missing');
      const retainedChunks: Buffer[] = [];
      for await (const chunk of retainedStream) retainedChunks.push(Buffer.from(chunk));
      expect(Buffer.concat(retainedChunks).equals(evidenceBytes)).toBeTruthy();
    });
  });
}
